### ISSUE TITLE
The packages keep installing and enabling by themselves.

### ISSUE THREAD

**Issue by franeklubi** [atom-community/atom-ide-base#93]
Opening another issue, because the other one got snubbed and locked without any explanation, and the current situation is apalling.

**Comment by aminya** [comment]
Someone needs to do the work. There is no need to open another issue.

Duplicate of #90

**Comment by mightypirate1** [comment]
I'm having issues too too with this package reinstalling itself repeatedly. I'm not able to solve it, and at the point where I might throw my computer out the window. Who put the work in to make this monstuosity? Am I supposed to reinstall atom from scratch to get rid of this?

**Comment by mightypirate1** [comment]
I struggled too with this issue too - it's crazy making. To others coming across this, go thru all the packages and uninstall everything with "atom-ide" in it. If you leave any, it will reinstall itself again. If you know similar tools that are less invasive, feel fell to pm!
